# Spring properties
spring:
  application:
     name: ZUUL  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                             # Template location for this application only



# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

# HTTP Server
server:
  port: 8001   # HTTP (Tomcat) puerto del microservicio